# Creates a lambda to run the fizzbuzz application
resource "aws_lambda_function" "fizzbuzz" {

  # filename generated by `make zip` command
  filename      = "../fizzbuzz.zip"
  function_name = "fizzbuzz"

  # python function to be called
  handler       = "fizzbuzz/main.lambda_handler"

  # asssume the role created allowing its execution
  role          = aws_iam_role.exec_role.arn

  # The filebase64sha256 function computes the SHA256 hash of the contents of a given file and encodes it with Base64.
  source_code_hash = filebase64sha256("../fizzbuzz.zip")

  # Mandatory version choose to run the following application
  runtime = "python3.8"

}